draft 1: videomoderation support
Cryptonomic/ImageProxy pull request #71
Opened 2021-10-30 07:48 UTC by SiddharthV1

draft version

2021-11-11 11:06 UTC, bhaskarkishore commented
@SiddharthV1 - This is a good starting point. Please review the comments. The next step would be remove all unnecessary code from this branch. We can then meet and talk about full integration.

2021-11-23 13:54 UTC, Taaseen-Ali requested changes

2021-11-23 13:54 UTC, Taaseen-Ali commented on src/aws/mod.rs
> +                    match Rekognition::get_moderation_results(
Switch to polling the sns periodically instead Rekognition

2021-11-23 13:54 UTC, Taaseen-Ali commented on src/aws/mod.rs
> +                tokio::task::spawn(async move {
Move this closure out into its own function

2021-11-23 13:54 UTC, Taaseen-Ali commented on src/aws/mod.rs
> +                        Ok(r) => {
Instead of doing these updates in the spawned thread, have master thread that iterates through the job table and updates accordingly

2021-11-23 13:54 UTC, Taaseen-Ali commented on src/rpc/mod.rs
> +                (status, vec![], Some(document.clone()))
How should we handle client side retries?

2022-06-01 03:56 UTC, bhaskarkishore commented
Closing as this feature is being redone as per a new roadmap, will revisit if required.

2022-06-01 03:56 UTC, closed without merging